# Generated by Django 4.2.6 on 2023-10-22 15:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("products", "0001_initial"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_number",
                    models.PositiveIntegerField(
                        auto_created=True, verbose_name="Номер заказа"
                    ),
                ),
                (
                    "ordering_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата оформления заказа"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Ordered", "Оформлен"),
                            ("In processing", "В обработке"),
                            ("Completed", "Комплектуется"),
                            ("Gathered", "Собран"),
                            ("In delivering", "Передан в доставку"),
                            ("Delivered", "Доставлен"),
                            ("Completed", "Завершен"),
                        ],
                        default="Оформлен",
                        max_length=50,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("Cash", "Наличные"),
                            ("By card on the website", "Картой на сайте"),
                            ("In getting by card", "Оплата картой курьеру"),
                        ],
                        default="Картой на сайте",
                        max_length=50,
                    ),
                ),
                ("is_paid", models.BooleanField(default=False)),
                ("comment", models.TextField(blank=True, max_length=400)),
                (
                    "delivery_method",
                    models.CharField(
                        choices=[
                            ("Point of delivery", "Пункт выдачи"),
                            ("By courier", "Курьером"),
                        ],
                        default="Курьером",
                        max_length=50,
                    ),
                ),
                (
                    "address",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.address",
                        verbose_name="Адрес покупателя",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заказ",
                "verbose_name_plural": "Заказы",
                "ordering": ["-ordering_date"],
            },
        ),
        migrations.CreateModel(
            name="ShoppingCart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(
                                1, "Разрешены значения от 1 до 10000"
                            ),
                            django.core.validators.MaxValueValidator(
                                10000, "Разрешены значения от 1 до 10000"
                            ),
                        ],
                        verbose_name="Количество",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Ordered", "Передано в заказ"),
                            ("In work", "В работе"),
                        ],
                        default="В работе",
                        max_length=50,
                    ),
                ),
                (
                    "packaging",
                    models.CharField(
                        choices=[
                            ("Add package", "Добавить упаковку"),
                            ("No package", "Без упаковки"),
                        ],
                        max_length=50,
                        verbose_name="Упаковка",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="orders.order",
                        verbose_name="Заказ",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="products.product",
                        verbose_name="Продукт в корзине",
                    ),
                ),
            ],
            options={
                "verbose_name": "Продукты в корзине",
                "verbose_name_plural": "Продукты в заказах",
            },
        ),
        migrations.AddField(
            model_name="order",
            name="products",
            field=models.ManyToManyField(
                through="orders.ShoppingCart",
                to="products.product",
                verbose_name="Продукты в заказе",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Покупатель",
            ),
        ),
        migrations.AddConstraint(
            model_name="shoppingcart",
            constraint=models.UniqueConstraint(
                fields=("order", "product"), name="unique_shopping_cart_products"
            ),
        ),
    ]
