# Generated by Django 4.2.6 on 2023-10-25 04:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_number",
                    models.PositiveIntegerField(
                        auto_created=True, verbose_name="Номер заказа"
                    ),
                ),
                (
                    "ordering_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата оформления заказа"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Ordered", "Оформлен"),
                            ("In processing", "В обработке"),
                            ("Completed", "Комплектуется"),
                            ("Gathered", "Собран"),
                            ("In delivering", "Передан в доставку"),
                            ("Delivered", "Доставлен"),
                            ("Completed", "Завершен"),
                        ],
                        default="Оформлен",
                        max_length=50,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("Cash", "Наличные"),
                            ("By card on the website", "Картой на сайте"),
                            ("In getting by card", "Оплата картой курьеру"),
                        ],
                        default="Картой на сайте",
                        max_length=50,
                    ),
                ),
                ("is_paid", models.BooleanField(default=False)),
                ("comment", models.TextField(blank=True, max_length=400)),
                (
                    "delivery_method",
                    models.CharField(
                        choices=[
                            ("Point of delivery", "Пункт выдачи"),
                            ("By courier", "Курьером"),
                        ],
                        default="Курьером",
                        max_length=50,
                    ),
                ),
                (
                    "package",
                    models.BooleanField(default=False, verbose_name="Упаковка"),
                ),
            ],
            options={
                "verbose_name": "Заказ",
                "verbose_name_plural": "Заказы",
                "ordering": ["-ordering_date"],
            },
        ),
        migrations.CreateModel(
            name="ShoppingCart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Ordered", "Передано в заказ"),
                            ("In work", "В работе"),
                        ],
                        default="В работе",
                        max_length=50,
                    ),
                ),
            ],
            options={
                "verbose_name": "Корзина",
                "verbose_name_plural": "Корзина",
            },
        ),
        migrations.CreateModel(
            name="ShoppingCartProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(
                                1, "Разрешены значения от 1 до 10000"
                            ),
                            django.core.validators.MaxValueValidator(
                                10000, "Разрешены значения от 1 до 10000"
                            ),
                        ],
                        verbose_name="Количество",
                    ),
                ),
            ],
            options={
                "verbose_name": "Продукты в корзине",
                "verbose_name_plural": "Продукты  в корзине",
            },
        ),
    ]
