# Generated by Django 4.2.7 on 2023-11-06 08:05

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0001_initial"),
        ("products", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Delivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "delivery_point",
                    models.CharField(max_length=150, verbose_name="Пункт выдачи"),
                ),
            ],
            options={
                "verbose_name": "Пункт выдачи",
                "verbose_name_plural": "Пункты выдачи",
            },
        ),
        migrations.CreateModel(
            name="ShoppingCart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Ordered", "Передано в заказ"),
                            ("In work", "В работе"),
                        ],
                        default="В работе",
                        max_length=50,
                    ),
                ),
                ("total_price", models.PositiveIntegerField(default=0)),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
            ],
            options={
                "verbose_name": "Корзина",
                "verbose_name_plural": "Корзина",
            },
        ),
        migrations.CreateModel(
            name="ShoppingCartProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(
                                1, "Разрешены значения от 1 до 10000"
                            ),
                            django.core.validators.MaxValueValidator(
                                10000, "Разрешены значения от 1 до 10000"
                            ),
                        ],
                        verbose_name="Количество",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="products.product",
                        verbose_name="Продукт в корзине",
                    ),
                ),
                (
                    "shopping_cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shopping_carts",
                        to="orders.shoppingcart",
                        verbose_name="Корзина",
                    ),
                ),
            ],
            options={
                "verbose_name": "Продукты в корзине",
                "verbose_name_plural": "Продукты  в корзине",
            },
        ),
        migrations.AddField(
            model_name="shoppingcart",
            name="products",
            field=models.ManyToManyField(
                through="orders.ShoppingCartProduct",
                to="products.product",
                verbose_name="Продукты в корзине",
            ),
        ),
        migrations.AddField(
            model_name="shoppingcart",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shopping_carts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Покупатель",
            ),
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_number",
                    models.PositiveIntegerField(default=1, verbose_name="Номер заказа"),
                ),
                (
                    "ordering_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата оформления заказа"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Ordered", "Оформлен"),
                            ("In processing", "В обработке"),
                            ("Completed", "Комплектуется"),
                            ("Gathered", "Собран"),
                            ("In delivering", "Передан в доставку"),
                            ("Delivered", "Доставлен"),
                            ("Completed", "Завершен"),
                        ],
                        default="Оформлен",
                        max_length=50,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("Cash", "Наличные"),
                            ("By card on the website", "Картой на сайте"),
                            ("In getting by card", "Оплата картой курьеру"),
                        ],
                        default="Картой на сайте",
                        max_length=50,
                    ),
                ),
                ("is_paid", models.BooleanField(default=False)),
                ("comment", models.TextField(blank=True, max_length=400)),
                (
                    "delivery_method",
                    models.CharField(
                        choices=[
                            ("Point of delivery", "Пункт выдачи"),
                            ("By courier", "Курьером"),
                        ],
                        default="Курьером",
                        max_length=50,
                    ),
                ),
                (
                    "package",
                    models.BooleanField(default=False, verbose_name="Упаковка"),
                ),
                (
                    "address",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.address",
                        verbose_name="Адрес покупателя",
                    ),
                ),
                (
                    "delivery_point",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="orders.delivery",
                        verbose_name="Пункт выдачи",
                    ),
                ),
                (
                    "shopping_cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="orders.shoppingcart",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Покупатель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заказ",
                "verbose_name_plural": "Заказы",
                "ordering": ["-ordering_date"],
            },
        ),
        migrations.AddConstraint(
            model_name="shoppingcartproduct",
            constraint=models.UniqueConstraint(
                fields=("shopping_cart", "product"),
                name="unique_shopping_cart_products",
            ),
        ),
    ]
