# Generated by Django 4.2.6 on 2023-10-22 16:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="shoppingcart",
            options={
                "verbose_name": "Продукты в корзине",
                "verbose_name_plural": "Продукты в заказе",
            },
        ),
        migrations.RenameField(
            model_name="shoppingcart",
            old_name="packaging",
            new_name="package",
        ),
    ]
