# Generated by Django 4.2.7 on 2023-11-08 13:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Ordered", "Оформлен"),
                    ("In processing", "В обработке"),
                    ("Collecting", "Комплектуется"),
                    ("Gathered", "Собран"),
                    ("In delivering", "Передан в доставку"),
                    ("Delivered", "Доставлен"),
                    ("Completed", "Завершен"),
                ],
                default="Ordered",
                max_length=50,
                verbose_name="Status",
            ),
        ),
    ]
