# Generated by Django 4.2.7 on 2023-11-08 06:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shoppingcart",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Created"
            ),
        ),
    ]
