# Generated by Django 4.2.6 on 2023-10-28 11:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="order_number",
        ),
    ]
