# Generated by Django 4.2.7 on 2023-11-04 22:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0004_remove_order_order_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_number",
            field=models.CharField(default="1", max_length=50, verbose_name="Number"),
        ),
    ]
