# Generated by Django 4.2.6 on 2023-10-29 15:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0005_alter_shoppingcart_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="shoppingcart",
            name="total_price",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
