# Generated by Django 4.2.7 on 2023-12-28 09:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0006_order_add_address_order_total_price_order_user_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("Payment at the point of delivery", "Оплата в пункте самовывоза"),
                    ("In getting by cash", "Оплата наличными курьеру"),
                    ("Online", "Оплата на сайте"),
                ],
                default="In getting by cash",
                max_length=50,
                verbose_name="Payment Method",
            ),
        ),
    ]
