# Generated by Django 4.2.7 on 2024-01-04 12:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_user_phone_number"),
        ("products", "0005_coupon_alter_promotion_promotion_type"),
        ("orders", "0007_alter_order_payment_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="coupon_applied",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="products.coupon",
                verbose_name="Coupon",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="coupon_discount",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MaxValueValidator(100)],
                verbose_name="Coupon %",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="users.address",
                verbose_name="User's address",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="delivery_point",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="orders.delivery",
                verbose_name="Delivery Point",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="products",
            field=models.ManyToManyField(
                related_name="orders",
                through="orders.OrderProduct",
                to="products.product",
                verbose_name="Продукты в заказе",
            ),
        ),
    ]
