# Generated by Django 4.2.7 on 2024-02-01 04:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0008_order_coupon_applied_order_coupon_discount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_number",
            field=models.CharField(max_length=50, unique=True, verbose_name="Number"),
        ),
    ]
