# Generated by Django 4.2.6 on 2023-10-19 09:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="Name"),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=100, unique=True, verbose_name="Slug"
                    ),
                ),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Component",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Component name",
                        max_length=100,
                        unique=True,
                        verbose_name="Name",
                    ),
                ),
            ],
            options={
                "verbose_name": "Component",
                "verbose_name_plural": "Components",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Producer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Producer name",
                        max_length=100,
                        unique=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "producer_type",
                    models.CharField(
                        choices=[
                            ("company", "Юридическое лицо"),
                            ("entrepreneur", "Индивидуальный предприниматель"),
                        ],
                        default="company",
                        max_length=12,
                        verbose_name="Producer type",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Brief information about the company or entrepreneur",
                        verbose_name="Description",
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        help_text="Legal address of the producers",
                        verbose_name="Address",
                    ),
                ),
            ],
            options={
                "verbose_name": "Producer",
                "verbose_name_plural": "Producers",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Promotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "promotion_type",
                    models.CharField(
                        choices=[
                            ("simple", "Простая скидка"),
                            ("birthday", "Скидка именинникам"),
                            ("loyalty_card", "Скидка по карте покупателя"),
                            (
                                "expired_soon",
                                "Скидка на товары с истекающим сроком годности",
                            ),
                            ("present", "Товар в подарок"),
                            ("two_for_one", "Два по цене одного"),
                            ("multiple_items", "Скидка при покупке нескольких штук"),
                        ],
                        default="simple",
                        max_length=14,
                        verbose_name="Promotion type",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Promotion name",
                        max_length=100,
                        unique=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "discount",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Percentage of a product price",
                        validators=[django.core.validators.MaxValueValidator(100)],
                        verbose_name="Discount",
                    ),
                ),
                (
                    "conditions",
                    models.TextField(
                        blank=True,
                        help_text="Conditions of the promotion",
                        verbose_name="Conditions",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Is this promotion valid now",
                        verbose_name="Active or not",
                    ),
                ),
                (
                    "is_constant",
                    models.BooleanField(
                        default=False,
                        help_text="Does this promotion have a time limits",
                        verbose_name="Constant or not",
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(
                        blank=True, verbose_name="Promotion start time"
                    ),
                ),
                (
                    "end_time",
                    models.DateTimeField(blank=True, verbose_name="Promotion end time"),
                ),
            ],
            options={
                "verbose_name": "Promotion",
                "verbose_name_plural": "Promotions",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Tag name",
                        max_length=100,
                        unique=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="Tag slug",
                        max_length=100,
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tag",
                "verbose_name_plural": "Tags",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Subcategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="Name"),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=100, unique=True, verbose_name="Slug"
                    ),
                ),
                (
                    "parent_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="products.category",
                        verbose_name="Category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subcategory",
                "verbose_name_plural": "Subcategories",
                "ordering": ["name"],
            },
        ),
    ]
