# Generated by Django 4.2.6 on 2023-10-26 07:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="promotion_quantity",
        ),
    ]
