# Generated by Django 4.2.6 on 2023-10-24 10:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productpromotion",
            options={
                "verbose_name": "ProductPromotion",
                "verbose_name_plural": "ProductPromotions",
            },
        ),
        migrations.AddConstraint(
            model_name="productpromotion",
            constraint=models.UniqueConstraint(
                fields=("product", "promotion"), name="unique_product_promotion"
            ),
        ),
    ]
