# Generated by Django 4.2.7 on 2023-12-15 06:35

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_alter_product_amount_alter_product_carbohydrates_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True,
                upload_to=products.models.Category.category_directory_path,
                verbose_name="Image",
            ),
        ),
        migrations.AddField(
            model_name="producer",
            name="image",
            field=models.ImageField(
                blank=True,
                upload_to=products.models.Producer.producer_directory_path,
                verbose_name="Image",
            ),
        ),
        migrations.AddField(
            model_name="promotion",
            name="image",
            field=models.ImageField(
                blank=True,
                upload_to=products.models.Promotion.promotion_directory_path,
                verbose_name="Image",
            ),
        ),
        migrations.AddField(
            model_name="promotion",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="Promotion slug",
                max_length=100,
                unique=True,
                verbose_name="Slug",
            ),
        ),
        migrations.AddField(
            model_name="subcategory",
            name="image",
            field=models.ImageField(
                blank=True,
                upload_to=products.models.Subcategory.subcategory_directory_path,
                verbose_name="Image",
            ),
        ),
        migrations.AddField(
            model_name="tag",
            name="image",
            field=models.ImageField(
                blank=True,
                upload_to=products.models.Tag.tag_directory_path,
                verbose_name="Image",
            ),
        ),
    ]
