# Generated by Django 4.2.7 on 2024-01-03 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_category_image_producer_image_promotion_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "promotion_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="products.promotion",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
            ],
            bases=("products.promotion",),
        ),
        migrations.AlterField(
            model_name="promotion",
            name="promotion_type",
            field=models.CharField(
                choices=[
                    ("simple", "Простая скидка"),
                    ("birthday", "Скидка именинникам"),
                    ("loyalty_card", "Скидка по карте покупателя"),
                    ("expired_soon", "Скидка на товары с истекающим сроком годности"),
                    ("present", "Товар в подарок"),
                    ("two_for_one", "Два по цене одного"),
                    ("multiple_items", "Скидка при покупке нескольких штук"),
                    ("coupon", "Промокод"),
                ],
                default="simple",
                max_length=14,
                verbose_name="Promotion type",
            ),
        ),
    ]
