# Generated by Django 4.2.7 on 2023-11-22 04:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import recipes.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("products", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductsInRecipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="productsinrecipe",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Products in recipe",
                "verbose_name_plural": "Products in recipes",
            },
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pub_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Recipe title")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        upload_to=recipes.models.Recipe.recipe_directory_path,
                        verbose_name="Dish image",
                    ),
                ),
                ("text", models.TextField(verbose_name="Recipe description")),
                (
                    "cooking_time",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Cooking time",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Recipe author",
                    ),
                ),
                (
                    "ingredients",
                    models.ManyToManyField(
                        related_name="recipes",
                        through="recipes.ProductsInRecipe",
                        to="products.product",
                        verbose_name="Ingredients",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recipe",
                "verbose_name_plural": "Recipes",
                "ordering": ["-pub_date"],
            },
        ),
        migrations.AddField(
            model_name="productsinrecipe",
            name="recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipeingredient",
                to="recipes.recipe",
                verbose_name="Рецепт",
            ),
        ),
    ]
