# Generated by Django 4.2.7 on 2024-01-12 04:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="servings_quantity",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Servings Quantity"
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="short_description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Short description"
            ),
        ),
    ]
