# Generated by Django 4.2.6 on 2023-10-25 20:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="region",
            field=models.CharField(
                choices=[
                    ("St. Petersburg", "Санкт-Петербург"),
                    ("Leningrad region", "Ленинградская область"),
                    ("Moscow", "Москва"),
                    ("Moscow region", "Московская область"),
                ],
                max_length=200,
                verbose_name="Region",
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="street_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Street", "Улица"),
                    ("Avenue", "Проспект"),
                    ("Passage", "Проезд"),
                    ("Square", "Площадь"),
                    ("Embankment", "Набережная"),
                    ("Blind alley", "Тупик"),
                ],
                max_length=100,
                null=True,
                verbose_name="Street_type",
            ),
        ),
    ]
