# Generated by Django 4.2.6 on 2023-10-27 18:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="useraddress",
            options={
                "verbose_name": "User Address",
                "verbose_name_plural": "User Addresses",
            },
        ),
    ]
