# Generated by Django 4.2.6 on 2023-10-26 18:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_address_region_alter_address_street_type"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="address",
            name="unique address",
        ),
        migrations.RemoveField(
            model_name="address",
            name="apartment",
        ),
        migrations.RemoveField(
            model_name="address",
            name="city",
        ),
        migrations.RemoveField(
            model_name="address",
            name="city_type",
        ),
        migrations.RemoveField(
            model_name="address",
            name="country",
        ),
        migrations.RemoveField(
            model_name="address",
            name="house",
        ),
        migrations.RemoveField(
            model_name="address",
            name="microdistrict",
        ),
        migrations.RemoveField(
            model_name="address",
            name="postal_code",
        ),
        migrations.RemoveField(
            model_name="address",
            name="region",
        ),
        migrations.RemoveField(
            model_name="address",
            name="street",
        ),
        migrations.RemoveField(
            model_name="address",
            name="street_type",
        ),
        migrations.RemoveField(
            model_name="user",
            name="address_quantity",
        ),
        migrations.AddField(
            model_name="address",
            name="address",
            field=models.TextField(default=1, verbose_name="Address"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="city",
            field=models.CharField(
                choices=[("Moscow", "Москва")], max_length=50, verbose_name="City"
            ),
        ),
    ]
