# Generated by Django 4.2.6 on 2023-10-29 22:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_useraddress_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraddress",
            name="priority_address",
            field=models.BooleanField(default=False),
        ),
    ]
