# Generated by Django 4.2.6 on 2023-10-30 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_useraddress_priority_address"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="useraddress",
            options={},
        ),
        migrations.RemoveConstraint(
            model_name="useraddress",
            name="unique_user_address",
        ),
        migrations.RemoveField(
            model_name="user",
            name="address",
        ),
        migrations.RemoveField(
            model_name="useraddress",
            name="address",
        ),
        migrations.RemoveField(
            model_name="useraddress",
            name="priority_address",
        ),
        migrations.RemoveField(
            model_name="useraddress",
            name="user",
        ),
        migrations.AddField(
            model_name="address",
            name="priority_address",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="address",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="addresses",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Address",
            ),
            preserve_default=False,
        ),
    ]
