# Generated by Django 4.2.6 on 2023-10-26 19:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_remove_address_unique_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                blank=True, max_length=150, unique=True, verbose_name="Username"
            ),
        ),
    ]
