# Generated by Django 4.2.7 on 2023-11-21 09:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=17,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Введен некорректный номер телефона. Введите номер телефона в форматах '+79999999999', '79999999999' или '89999999999'.",
                        regex="^(\\+7|7|8)\\d{10}$",
                    )
                ],
            ),
        ),
    ]
