# Generated by Django 4.2.7 on 2023-11-21 08:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=17,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Введен некорректный номер телефона. Введите номер телефона в формате '+79999999999'.",
                        regex="^\\+?1?\\d{11}$",
                    )
                ],
            ),
        ),
    ]
