# Generated by Django 4.2.6 on 2023-10-30 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_useraddress_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="address",
            name="user",
        ),
        migrations.AddField(
            model_name="user",
            name="address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="users.address",
                verbose_name="Addresses",
            ),
        ),
    ]
